# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: stratos
description: Upload your Stadia captures to Google Drive
version: 0.2.0
homepage: https://stratos.refi64.com/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  aspen: ^0.3.0
  aspen_assets: ^0.3.0
  # Slightly older version to avoid issues with freezed's deps.
  build: ^1.3.0
  freezed_annotation: ^0.12.0
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.11
  http: ^0.12.2
  intl: ^0.16.1
  js: ^0.6.1
  json_annotation: ^3.0.1
  # Latest logger breaks on dart2js
  logger: 0.9.3
  meta: ^1.2.3
  rxdart: ^0.24.1
  stack_trace: ^1.9.3

dev_dependencies:
  aspen_builder: ^0.3.0
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  freezed: ^0.12.1
  json_serializable: ^3.3.0
  pedantic: ^1.9.0
